from telebot import types

main_keyboard = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton('Найти случайный фильм')
item2 = types.KeyboardButton('Фильтр: рейтинг КиноПоиска')
item3 = types.KeyboardButton('Фильтр: рейтинг IMDB')
item4 = types.KeyboardButton('Фильтр: жанр')
main_keyboard.add(item1)
main_keyboard.add(item2)
main_keyboard.add(item3)
main_keyboard.add(item4)

keyboard_genres = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1kb2 = types.KeyboardButton('Комедия')
item2kb2 = types.KeyboardButton('Драма')
item3kb2 = types.KeyboardButton('Фантастика')
item4kb2 = types.KeyboardButton('приключения')
item5kb2 = types.KeyboardButton('Боевик')
item6kb2 = types.KeyboardButton('Мелодрама')
item7kb2 = types.KeyboardButton('Вестерн')
item8kb2 = types.KeyboardButton('Детектив')
item9kb2 = types.KeyboardButton('Триллер')
item10kb2 = types.KeyboardButton('История')
keyboard_genres.add(item1kb2)
keyboard_genres.add(item2kb2)
keyboard_genres.add(item3kb2)
keyboard_genres.add(item4kb2)
keyboard_genres.add(item5kb2)
keyboard_genres.add(item6kb2)
keyboard_genres.add(item7kb2)
keyboard_genres.add(item8kb2)
keyboard_genres.add(item9kb2)
keyboard_genres.add(item10kb2)
