from telebot import types

main_keyboard = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton('Найти случайный фильм')
item2 = types.KeyboardButton('Фильтры')
main_keyboard.add(item1)
main_keyboard.add(item2)

keyboard_filters = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1kb3 = types.KeyboardButton('рейтинг КиноПоиска')
item2kb3 = types.KeyboardButton('рейтинг IMDB')
item3kb3 = types.KeyboardButton('жанр')
keyboard_filters.add(item1kb3)
keyboard_filters.add(item2kb3)
keyboard_filters.add(item3kb3)

keyboard_genres = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1kb2 = types.KeyboardButton('Комедия')
item2kb2 = types.KeyboardButton('Драма')
item3kb2 = types.KeyboardButton('Фантастика')
item4kb2 = types.KeyboardButton('Приключения')
item5kb2 = types.KeyboardButton('Боевик')
item6kb2 = types.KeyboardButton('Мелодрама')
item7kb2 = types.KeyboardButton('Вестерн')
item8kb2 = types.KeyboardButton('Детектив')
item9kb2 = types.KeyboardButton('Триллер')
item10kb2 = types.KeyboardButton('История')
item11kb2 = types.KeyboardButton('Ужасы')
keyboard_genres.add(item1kb2, item2kb2)
keyboard_genres.add(item3kb2, item4kb2)
keyboard_genres.add(item5kb2, item6kb2)
keyboard_genres.add(item7kb2, item8kb2)
keyboard_genres.add(item9kb2, item10kb2)
keyboard_genres.add(item11kb2)
